### ISSUE TITLE
Created icns file seems broken

### ISSUE THREAD

**Issue by NiklasEi** [JoshuaBrest/icns#1]
First of all: thank you for this crate, the API looks simple and nice :slightly_smiling_face: 

I do not have a mac to properly test it, but the icns file created by the current example does not have a preview on my system and fails to load in inkscape (while others successfully display). Is the icns file creation already supposed to be usable?

**Comment by JoshBashed** [comment]
That seems very odd. I will have to look into this.

**Comment by JoshBashed** [comment]
I think I fixed this in v1.0.2, try it!

**Comment by NiklasEi** [comment]
Yes, I now get a preview and Inkscape also seems fine with the icns file, thank you.
